package org.semmelweis.university.anatomyapp.ui.learn;

class LearnConstants {

    static final String [] THESISES = {
            "1. Hámszövet",
            "2. Kötőszövet",
            "3. Zsírszövet; Porcszövet",
            "4. Csontszövet",
            "5. Izomszövet",
            "6. Az ivarsejtek kialakulása,  Ivarsejtek; Megtermékenyítés;",
            "7. A magzat kialakulása, A magzat fejlődése",
            "8. Extrauterin fejlődés",
            "9. Csontokról általában; A csontok szerkezete, fejlődése, növekedése",
            "10. A csontok járulékos alkotórészei;   A csontok összeköttetései",
            "11. Az arckoponya",
            "12. Az agykoponya",
            "13. A koponyatető és a koponyaalap",
            "14. A koponya üregei",
            "15. A mandibula és ízülete",
            "16. A sternum, a bordák, ezek összeköttetései; A mellkas",
            "17. A csigolyák és a gerinc",
            "18. A vállöv csontjai és ízületei",
            "19. Humerus; Vállízület",
            "20. Az alkar csontjai;   A könyökízület",
            "21. A kéz csontjai és ízületei",
            "22. A medencecsont és összeköttetései",
            "23. A medence egészben",
            "24. A combcsont és a csípőízület",
            "25. A lábszár csontjai és a térdízület",
            "26. A láb csontjai és ízületei; A láb egészben",
            "27. A vázizmokról általában; Az izom szerkezete, felépítése, összetétele",
            "28. A fejizmok",
            "29. A mellkas izmai",
            "30. A hátizmok",
            "31. A nyakizmok",
            "32. A hasizmok",
            "33. A sérvcsatornák",
            "34. A felsővégtag izmai",
            "35. Az alsó végtag izmai",
            "36. A szív külső leírása; helyzete, vetülete",
            "37. A szív üregei, szájadékai, billentyűi",
            "38. A szívfal szerkezete és a szívburok",
            "39. A szív beidegzése",
            "40. A szív saját erei",
            "41. Az erekről általában, az erek szerkezete; összeköttetései; Vérkörök",
            "42. Az aorta ascendens, az arcus aortae és ágaik",
            "43. Az aorta descendens és ágai",
            "44. A nagyvérkör vénái",
            "45. A magzati vérkeringés",
            "46. A nyirokrendszer, nyirokszervek, nyirokkeringés",
            "47. A nyirokcsomó és a lép",
            "48. A mandulák és a csecsemőmirigy",
            "49. A vér és alakos elemei, vérplazma",
            "50. A csontvelő és a vérképzés; A vörösvértestek és a fehérvérsejtek fejlődése"
    };
}
